# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: "Construir Aplicación"
  jobs:
  - job: BuildJob
    steps:
    - script: dotnet build simulated-device-2.csproj --configuration $(buildConfiguration)
      displayName: 'Compilar proyecto'

- stage: Deploy
  displayName: "Desplegar en VM Ubuntu"
  dependsOn: Build
  jobs:
  - deployment: DeploySimulatedDevice
    displayName: 'Desplegar aplicación en la VM'
    environment: 'VM-Azure'  
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'DevicesSimulatorSSH'  # Nombre de tu conexión SSH configurada a la máquina virtual
              runOptions: 'commands'
              readyTimeout: '30000'
              # Comandos para desplegar y ejecutar la aplicación en la VM
              commands: |
                cd /home/azureuser/app
                dotnet build simulated-device-2.csproj --configuration $(buildConfiguration)
                nohup dotnet run --project simulated-device-2.csproj --configuration $(buildConfiguration) > app.log 2>&1 &
            displayName: 'Ejecutar aplicación en la VM'