trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: 'Construir y subir imagen Docker'
  jobs:
  - job: BuildPush
    displayName: 'Construir y subir'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Construir imagen Docker'
      inputs:
        command: 'build'
        repository: simulatedregistry.azurecr.io/simulated-devices
        dockerfile: 'Dockerfile'
        tags: '$(tag)'
        containerRegistry: 'SimulatedRegistry'

    - task: Docker@2
      displayName: 'Subir imagen a ACR'
      inputs:
        command: 'push'
        repository: simulatedregistry.azurecr.io/simulated-devices
        tags: '$(tag)'
        containerRegistry: 'SimulatedRegistry'
